version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: "wms-0.0.1-SNAPSHOT.jar"
		container_name: wms
		ports:
			- "8080:8080"
		environment:
			SPRING_PROFILES_AVTIVE: prod
			SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
			SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
			SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
		restart: always
